package com.codelace.codelace.service;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.web.multipart.MultipartFile;

import com.codelace.codelace.exception.ResourceNotFoundException;
import com.codelace.codelace.mapper.PostMapper;
import com.codelace.codelace.mapper.StudentMapper;
import com.codelace.codelace.model.dto.PostByProjectResponseDTO;
import com.codelace.codelace.model.dto.PostByStudentResponseDTO;
import com.codelace.codelace.model.dto.PostRequestDTO;
import com.codelace.codelace.model.dto.PostResponseDTO;
import com.codelace.codelace.model.dto.PostResponseIdDTO;
import com.codelace.codelace.model.dto.StudentResponseDTO;
import com.codelace.codelace.model.entity.Comment;
import com.codelace.codelace.model.entity.Post;
import com.codelace.codelace.model.entity.Project;
import com.codelace.codelace.model.entity.Rocket;
import com.codelace.codelace.model.entity.Student;
import com.codelace.codelace.repository.CommentRepository;
import com.codelace.codelace.repository.PostRepository;
import com.codelace.codelace.repository.ProjectRepository;
import com.codelace.codelace.repository.RocketRepository;
import com.codelace.codelace.repository.StudentRepository;

@ExtendWith(MockitoExtension.class)
public class PostServiceTest {
    // Instance mapper
	@Mock
	private PostMapper postMapper;

	@Mock
	private StudentMapper studentMapper;

    @Mock
	private PostRepository postRepository;

	@Mock
	private StudentRepository studentRepository;

	@Mock
	private ProjectRepository projectRepository;

	@Mock
	private RocketRepository rocketRepository;

	@Mock
	private CommentRepository commentRepository;
    // Test Service
	@InjectMocks
	private PostService postService;
	
	@Test
	public void testGetPostById_ExistingId() {
		// Arrange
		Long postId = 1L;

		Student student = new Student();
		student.setId(1L);
		student.setUsername("student1");
		student.setStatus("active");
		student.setDescription("Descripcion del estudiante 1");
		student.setEmail("pepito@hotmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image3 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image3));

		Project project = new Project();
		project.setId(1L);
		project.setTitle("Proyecto 1");

		Post post = new Post();
		post.setId(postId);
		post.setStudent(student);
		post.setProject(project);
		post.setDemoUrl("desplegado.com");
		post.setRepoUrl("github.com");
		post.setDescription("Proyecto bello");
		post.setDate(LocalDate.now());
		String base64Image = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		post.setImage(Base64.getDecoder().decode(base64Image));

		// Mocking Repository
		when(postRepository.findById(postId)).thenReturn(Optional.of(post));

		Rocket rocket1 = new Rocket();
		Rocket rocket2 = new Rocket();
		rocket1.setId(1L);
		rocket2.setId(2L);
		List<Rocket> rockets = Arrays.asList(rocket1, rocket2);

		when(rocketRepository.findAllByPostAndStudent(post, post.getStudent())).thenReturn(Optional.of(rockets));

		Comment comment1 = new Comment();
		Comment comment2 = new Comment();
		comment1.setId(1L);
		comment2.setId(2L);
		List<Comment> comments = Arrays.asList(comment1, comment2);

		when(commentRepository.findAllByPostAndStudent(post, post.getStudent())).thenReturn(Optional.of(comments));
	
		when(projectRepository.findById(post.getProject().getId())).thenReturn(Optional.of(project));

		StudentResponseDTO studentResponseDTO = new StudentResponseDTO();
		studentResponseDTO.setId(student.getId());
		studentResponseDTO.setUsername(student.getUsername());
		studentResponseDTO.setStatus(student.getStatus());
		studentResponseDTO.setDescription(student.getDescription());
		studentResponseDTO.setProfile_picture(student.getProfile_picture());
		
		// Mocking mapper
		PostResponseIdDTO responseDTO = new PostResponseIdDTO();
		responseDTO.setId(post.getId());
		responseDTO.setStudent(studentResponseDTO);
		responseDTO.setRockets((long) rockets.size());
		responseDTO.setComments((long) comments.size());
		responseDTO.setDemoUrl(post.getDemoUrl());
		responseDTO.setRepoUrl(post.getRepoUrl());
		responseDTO.setDescription(post.getDescription());
		responseDTO.setTitle(project.getTitle());
		responseDTO.setDate(post.getDate());
		responseDTO.setImage(post.getImage());

		when(postMapper.convertToResponseIdDTO(post)).thenReturn(responseDTO);

		// Act
		PostResponseIdDTO result = postService.getPostById(postId);

		// Assert
		assertNotNull(result);
		assertEquals(postId, result.getId());

		// Verify that repository and mapper methods were called
		verify(postRepository, times(1)).findById(postId);
		verify(rocketRepository, times(1)).findAllByPostAndStudent(post, post.getStudent());
		verify(commentRepository, times(1)).findAllByPostAndStudent(post, post.getStudent());
		verify(projectRepository, times(1)).findById(post.getProject().getId());
		verify(postMapper, times(1)).convertToResponseIdDTO(post);
	}

	@Test
	public void testGetPostById_PostNotFound() {
		// Arrange
		Long postId = 999L;

		when(postRepository.findById(postId)).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getPostById(postId));
	}

	@Test
	public void testGetPostById_ProjectNotFound() {
		// Arrange
		Long postId = 999L;

		Student student = new Student();
		student.setId(1L);
		student.setUsername("student1");
		student.setStatus("active");
		student.setDescription("Descripcion del estudiante 1");
		student.setEmail("pepito@hotmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image2 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image2));

		Project project = new Project();
		project.setId(1L);
		project.setTitle("Proyecto 1");

		Post post = new Post();
		post.setId(postId);
		post.setStudent(student);
		post.setProject(project);
		post.setDemoUrl("desplegado.com");
		post.setRepoUrl("github.com");
		post.setDescription("Proyecto bello");
		post.setDate(LocalDate.now());
		String base64Image = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		post.setImage(Base64.getDecoder().decode(base64Image));

		when(postRepository.findById(postId)).thenReturn(Optional.of(post));

		when(projectRepository.findById(post.getProject().getId())).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getPostById(postId));

		// Verify that repository and mapper methods were called
		verify(postRepository, times(1)).findById(postId);
		verify(projectRepository, times(1)).findById(post.getProject().getId());
	}
    
	@Test
    public void testGetAllPosts(){
        // Mocking mapper
		Student student1 = new Student();
		Student student2 = new Student();
		student1.setId(1L);
		student1.setUsername("student1");
		student1.setEmail("student1@gmail.com");
		student1.setPwd("contrasenafacilita");

		student2.setId(2L);
		student2.setUsername("student2");
		student2.setEmail("student2@gmail.com");
		student2.setPwd("contrasenafacilita2");

		List<Object[]> posts = new ArrayList<>(List.of(
			new Object[] { 1L, student1, 10L, 5L, LocalDate.parse("2024-01-01"), null },
			new Object[] { 2L, student2, 15L, 10L, LocalDate.parse("2024-03-10"), null }
		));

		List<PostByProjectResponseDTO> expectedResponse = posts.stream()
				.map(postData -> {
					PostByProjectResponseDTO postByProjectResponse = new PostByProjectResponseDTO();
					postByProjectResponse.setId((Long) postData[0]);
					postByProjectResponse.setStudent((Student) postData[1]);
					postByProjectResponse.setRockets((Long) postData[2]);
					postByProjectResponse.setComments((Long) postData[3]);
					postByProjectResponse.setDate((LocalDate) postData[4]);
					postByProjectResponse.setImage((byte[]) postData[5]);
					return postByProjectResponse;
				})
				.collect(Collectors.toList());

		when(postRepository.findAllPosts()).thenReturn(posts);

        // Act
		List<PostByProjectResponseDTO> result = postService.getAllPosts();

		// Assert
		assertNotNull(result);
		assertEquals(expectedResponse.size(), result.size());

		// Verify that repository and mapper methods were called
		verify(postRepository, times(1)).findAllPosts();
    }

	@Test
	public void testCreatePost_Successful() {
		// Arrange
		PostRequestDTO postRequestDTO = new PostRequestDTO();
		postRequestDTO.setDemoUrl("desplegado.com");
		postRequestDTO.setRepoUrl("github.com");
		postRequestDTO.setDescription("Proyecto bello");

		String contentType = "image/png";
		String name = "Nombre de foto";
		String base64Image = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYVFRgWFRYYGBgaGBgYGhgYGhgYGBgYGBgZGRgYGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISHjQrJCE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ/ND80Mf/AABEIAOEA4QMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAEAAIDBQYBB//EADIQAAIBAwMDAwMDBAIDAQAAAAABAgMEEQUSITFBUQYiYTJxgRORsVKhwdFC8CMzghT/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABQT/xAAgEQEBAQEBAAMBAQADAAAAAAAAAQIRIQMSMUFREyIy/9oADAMBAAIRAxEAPwDITiB3FHDyi0nAHnDyA4SitwZZ2vJDGDi+FlFnpTbljt4YeNzq1jpSmnKPRx4XyWFDRFCMW3jhZLnQKEdn+Am8o9l0BrX1VziUZpkIRilBpljFsw9dTpvdCTQyOv1U/qF/5v8ATf8AH/jfYGykZqw9R5WJr8l3aX0Kn0tGm5S3NieTZzYEOKRzI6aGNMcqIRCBIomYJ+gMqtRRNWngrq9TPCB00iCU3KRIoBVtZtLLQo0+RbBchS4CqMBQiNr1u0TcZDf3PG1Ffb2izulyGKm+vcc6bwNI1cyksIinIeyKXUpIRNT56kuBkEdkzVoTGs6cSFrFlCFhHAC8jZHOBNJDUmzQpWllKbxF8mj0/wBNzg90pL9mT+maKzmUcJdzSXLXVdBda4rnPXbCjsjhElzDgVnLsPrSRHWvstMqK/hnKMxfQ2s11yuWVF1RTeMEbOGnVJGpwSULqUXmLaI6trJNxS8jYUnFrI01xrGr0f1M1JQqfubWjKMkpReUzxa7nh4+TRaL6mqUlGMuYL+Cudp6y9OOSlgCsdUhVinGSz4Ja8ysvYlc+oLqQywo5eWhTjuYdSp7Ym6NgqMUDVoE1GZHcGgB2hkoDZ1COVUaZBKmkR1J5IlNiQ0yXpk5DKS5yKsyWjHgpJ/A6lY0cxjROt11jd4mhYBRNwIdu+BCi8rjTz0NDo2jxxvnn4HaVpOVulwXcntjhC6+TOVPj+PoW7j7WocA9hdSj7Zk7YPW4PLr5O16M44uKV0opsiurpYUsrnj8lNG57EU6jnJLHEOF931/Zfyaa62pxaSnkHqxAbnUI011/ADD1NCUsSi18rlG5aWbn5R9eGOUuQKtS4XIa7qE45hJS+3YHkhb4aKO4tZuTl2FQ54DriXDAYT2fkaUtE29zKk8xm1jtk1Oler4SxGpw+mTF1YbYOT6lfQy+R86JXt9hVjPmLTQfUn2PGtL1epS5jJ8djY6N6uhLiosPyUmi2NvBqPUFu6+eEDR1CE17JJjMlMks4WTj5HpHYxKkpsYinwh7ZHUlwboBm8yDIrggt4c5CEU/jRxjTrG5JUYUjgjoouYEIQeQAbhtWAOvIfc3uOAJ3cWczWvs6WcyQ2cga5kWGxNENeisCZaqRTeSO/vlSjtTzL/LHXT2ZfOewNY6e5S3z58IrlD5L/ABUzoVKrzh8/cjuNHnFZ6myVNdlgbOCwUzbEfowdK4cHw2mjW6LWjWj19yX4M7rVpsm2k8Mk9O3WyaXlj2faehnVzeNFe2soLO3d8rx9jOTk5T6YWeh6BB5X4ArjT4SeXFZ8rgh3j0SszdUt0MFa8QRqLzTpbWoNPjo+pm7+2lFYaaY2aFDRqPITCYJRWFz1HKfI0pVtbalOD9snwaHSvVnKjU6dMmJrzw0yKVXwUzrhbnr3C2qxklKLymTHjWk+pKtB4i214fQ0dv69ba3QL53Erlv6nQHqSILHUoVoKUX+B/1SRTPKS+C6MMIeJdDjGoQ1jWdycEvR6SOHDuAcM6IXIgsra1gpclXc2DjyadLjgguKOU0cqx0ZpkP/ANTi8BLvU0R3+mvLaBYWsspdu4sG2SJXbqcsvp4CZRx/oc+CGc1nqUnYhztNchkpCbOZQ/Rs5FXr1PdDPgy1CW2Sfhmyuqe6LXwzGXEMSa+Sub5x5vknL16Rp1bfCLCW8lH6Zr7oY8F3kjqcq+PYjnAGvVFQbkk0l3DZxyUPqWtiMYLrJ5f2QJ7R5xmLjh588jY0+426XPPbgIjHKx4S/uVIr7mfIoPKO3du1y0MprCD+BXVAntoLPJxIlow8BnaVrfTFRqWE+PBurOnxlmG9LUXv5R6DThhI9nxTz1LZzI5EsiGTG0WFI4LIsiWs4JCEjQXcCEIwk+ECRr5lg7Tr54Fc08e5HKdAJVecoqbiajwFV7lRy30wZqtqMZzaT5DnPQ1rzgyrdPsQuowGNfcwmEhrmwkvE6kJI51F06A9NXZcmV1SlibNRJFLrlF8SX5K4qHyZ676butk9rfXsbWLR51YT2TUl2N5aVlOCkbeSfHrngsxuvXKU3J8vol4S6GnvLnZH5fCMJrss1PuLmf1bV8DOe/r9w2mvb/ACCWdPMi2m4xWPjp4Kc9J1C6e9NvokVE5JNpeQ6rdcNIA2jcLRNOXAVSWASiiWE+QwG+9LPKTa6dzYxPPdAjVaWyLS8m2tP1Nq34PXi+JanaMbI5D5MjbNqtHDh0TBzrEcEIH8Y4Q3IgMBnTcZBdZ7oP7EtSnujx2BISzlPwcyeOj1n9RoxcXHPVGB1G0qUJuXWPlG9vINSefJWX9CM4NS8cBx4n8mesfbapjqy2oaxF/cqXp0G2m8f7AK9rKEuHwen69ea71mtvSrbkSSZkbDWHB4kaG0vozXBLWOK53KMZDe0t8Gu/UcpBEVxwLnyqanYykY7eGaX09drGxsrdTtHnclwEaFbvO5lrZxGZ9H6hUcqiX/GK/uZbVHuqNmj1SpiOV3ZmYQbnLPyxMw1EWK2vL6YYJdXTc3gsJw/8Sa64Ku2p7pPyP+AJ/QePvj/eQapL3bV24Ly4pYXH9OP7FDRj7/yMUa44iorqzrW1/I+EH2WWSqio8y5fhf5NAa/0frGfZLj5NqpZPHbW5cZxfRJ9j1ixqZhF+Uj0Y10tgiQxyOyfA1jX9J13ImxDWzMR3IxsW7g0au7hDdwgAJt59iC8tf8AlH9hy4YUuhzudnHv+3GTv554ksfJUVl2Zs9R02M0ZavauMnGWeOjF+tlN2Vnr+ySW6JS103w10NZdWuVlMpqiUX7oqS/73KZ+Sz9R38Uvsqtt7BTWGvyNjbyoTUU/bkurWkpf+uW1/0v/ZFe2039Uc/wVupYjMWUZSlnD8htNMrtPTfDWGi1hHjJHT0Z/PT/ANPdw0FQt0ovCwhlODysB0oe3Hhf3FyNZLVoOS2rjnJUW0ec/Beapw2vj+SttodclZ/hNJKtP2xjnHd/YjsaC35/Iy4q5X/zgKsIN8/ZDyE6IuKXt/d/gzcViTwu5tJWrcH8lXDSlF56sP1L022pYj4IriUUsIJq0pdM4RW1aTXyHnAtMklnJ6d6fr7qUfsjzOnhtJ+T1DR6cVTio+B8SgsnI4cOJliuykRykKchmQ2FtOycchu4a5AsY7IiPIgCsdoVSjkHCaB4ZHq1UkqZX3lrGXVFtGOURVqZT6zhZrlYXU7Hl7UUV5ZZ4ksfJ6DdW2U+PyUd9bpxxjLJXPqn26wcqUqcsx7eDSabfRqRW7r8jLm1ygH9PY8o3LBWdWEE+OPsKjBz4islRUuQ/RNQ2y5F1TSTi6sKLb54wTXS25DVcqSyVGo1so2eFs4zmpS97bK6c8JpBd/ym/nJR3NfL/BXKWrw6jFykoryaewUIRzJpJdWzOWaxyU2uarNz2Z9qfK8l85iWtcb669U21NfWn8R5M7eetYNvbBvn7GHqyy20sDBuJ/atjLX3KKlt4bwGUbjcs8mbs6OYwj85NDt2xwJf08toqxpudSKwnyj06ygowSSwYb0tZylLf2RuqMGl1GyNqdsamNkzm4r/U3WROWDs5rAPu3MahEjmNbOSGuQonCItx0wrinNSQRQmUdGo49GmWdtUyc/N69mouIPgdU6EVvPKH1UsFp+JWcoOrhlHewWQu+cuxTXVZp4beSVvDSBrqnhMo7gtq91tXLK+pFTW6Il11WRTuGXgOtKah1Y79PaDKGZfYSnk8XUL9xWM8A11dNoFjEiqrEWPCaVuo3HGE+5UTfIVdS9xXVp8l8x59X0e7pRh8mcu6LbcvIVOrlh1GEWuSsqdnYzig/ARbWsm+hoadrRzzIKhXow+mOWa68aZhum2eyO6XX5E6u+e1ecA91fSnwuF4Ln0npLqT3y+lA/R5G09PWahBIvYsGhBRSS7D/1B5OF16kmyKTOuWSCtMqT+uSZ3IO5joyBL6Y6UzkpcELYnINBJvEQbxA6Kwa+M/gbT9ryuP3K+NKqukv7kT355mv3OXmvfcxsbO4yGTmsdTI2104/81+5e2N0prqn9i2dI6yhrzeWA3NCM18lpXhzyiruabjygabNZy9o7ZNS6ElnGGPb3DL233r5ALWm4vaxJFPsEu6bzwDwpsO1JODi8cN8hkrPEU/ItimfYqtpy7pYg2GTp9ga/wDoaHxE9MpfywU9zIstReGUtSeWXnjzaKC5CWiGnEJjAYqHYSQi/AVRoF1pejucl4NzpugdH0idaaWMLPLPUdM02FGCil06s7pekxpxXHIbOJaZ4W1FOWBJpLLGzgRuk31fQMK7OqscAdSpgInTwyGdBPuG9AyNTydcxSp47jHBmkDru4bUnhCcAW5Zhd/U+RAO5nTC0Dh4AKlHL5S+4ck/JHOOTkuhfVVcwS6t/gK0XUYwljnOSG8n2zgoZXO2Tw8Mpmk09XpVFUjkGuKXYzfpbVtzUX0NdcR4yWkTkUlShtZyVqpcrhlmkmcVNIP0a+fqnurFSjyiOrhxS8Iupoz1/Bxmsd2DWfFPh16CrLkCuY5RZXiwVleXAmer7zLGW1an1KKFBtmn1ChKWcIAjabVyXjw7nKBhQQTbU02kKpDPQItaTXLDE60mn6PFxTa+TTaVaJPCXQz2lXeXtyzY6dCWMprkfOet0a3hA82PqzfjP2B6lZFf4Tpk5CjIhlUOqXBsT1qjqS5Gbxk5kSmHv8A2ZNOZH+qcqS4BHUDqcD9T1KoJUmKU8g85E+jxJuEQ7xG6y4lc57jVcS7vgrFXXYmVVPucma66dy7ex3d1+5SVLTa2/5LGtOOOAKpVfbkeeJ0zSrmUKi8Z5PVKVRTgmueDy5UVJcdTQemdWdNuE3xxgtmkrQRs9snJN/vwFqfHITBxmsohqwKNagnMp9VlymG3DfYrHVxNOXQw5knpisJz5SJHoqivfyy5truDXtaIby6i+4cydbfyW+MxfWsUuCguLTL4kjSXTg08yWPuUdW4pRb2vcx+vPehIWOOmGQVpRTxnDJZ6hKXHT7dV8/JBVnGXE+r6TXR/f5N0EtnUcZJ9UejaPfxnBY8Hlk3KD+C69PatJTSb4fA2NcLXoFSo2wWoKNXjgjqTK2kiNvkfKeERKR2tPgOWoacxqmRTmM3A/phc5e0CcyWMsoElIfX4WOykRyY2UxjmQonbjpHkRmSXNNxYFXqNGguKGUUl7aM5PHUBRuV3GXE1hbe4LOO19CGpWaftLZT0sJOUVuzyguw1CL5muSqd6+FN8cZRK7qEcSXnoOT8ekaJq6cVGXBdVZJrqebWuqRccpYx+5LP1ZKPCbGzoL621eOSsuKaM/T9XPPKINT9QOa9vA/Qo+5qxhzux8ZM3e6rKTajJ4KytdSm+W2RRjl4yH7J8vU9apPHLb/JBTrtPx2GVoT6Mjopp8rKN0Es6zzt/Z+PgdCtx7llZxKPh/1ImhTi0njnJY0LXd0ijDycAwT4X1RfR/4ZLRtmnujlfHgsqdtFcNr7Crw2/Sx4Rd6RcyccNlhKoUmlVl0b5LNTLT1OwRGRHWmRSqEM6g8vANnIicxk58kTmLR6Poz4A6ssHadTBDcy5Hv/kP6UpjHMY5DJSIid+oIhz8iCLWMrr3uIRyY6bPXvUrKn1CEVz+J6DVepDV6o6IclW+nfU/sC3X1v7iEaN/Ch/kmrfSdEMWgYdRsvrQhBATAUujEIZN226fkubToIQZ+iiX1f8AfI+v9X4EIaFqS0+ouYCEWySuzIJCENSoJnBCBWcGVxCHv4H9RIZIQiY1EIQgM//Z";
		byte[] content = Base64.getDecoder().decode(base64Image);
		MultipartFile multipartFile = new MockMultipartFile(name, name, contentType, content);
		postRequestDTO.setImage(multipartFile);

		Project project = new Project();
		project.setId(1L);
		project.setTitle("Proyecto 1");
		project.setDescription("Descripcion proyecto 1");
		String base64Image2 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		project.setImage(Base64.getDecoder().decode(base64Image2));
		project.setLevel(1);

		Student student = new Student();
		student.setId(1L);
		student.setUsername("student1");
		student.setStatus("active");
		student.setDescription("Descripcion del estudiante 1");
		student.setEmail("pepito@hotmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image3 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image3));

		when(projectRepository.findById(postRequestDTO.getProject())).thenReturn(Optional.of(project));
		when(studentRepository.findById(postRequestDTO.getStudent())).thenReturn(Optional.of(student));

		Post post = new Post();
		post.setId(1L);
		post.setDemoUrl(postRequestDTO.getDemoUrl());
		post.setRepoUrl(postRequestDTO.getRepoUrl());
		post.setDescription(postRequestDTO.getDescription());
		try {
			post.setImage(postRequestDTO.getImage().getBytes());
		}
		catch (IOException e) {
			e.printStackTrace(); 
		}

		when(postMapper.convertToEntity(postRequestDTO)).thenReturn(post);

		post.setProject(project);
		post.setStudent(student);
		post.setDate(LocalDate.now());

		when(postRepository.save(post)).thenReturn(post);

		StudentResponseDTO studentResponseDTO = new StudentResponseDTO();
		studentResponseDTO.setId(student.getId());
		studentResponseDTO.setUsername(student.getUsername());
		studentResponseDTO.setStatus(student.getStatus());
		studentResponseDTO.setDescription(student.getDescription());
		studentResponseDTO.setProfile_picture(student.getProfile_picture());

		PostResponseDTO responseDTO = new PostResponseDTO();
		responseDTO.setId(post.getId());
		responseDTO.setStudent(studentResponseDTO);
		responseDTO.setDemoUrl(post.getDemoUrl());
		responseDTO.setRepoUrl(post.getRepoUrl());
		responseDTO.setDescription(post.getDescription());
		responseDTO.setDate(post.getDate());
		responseDTO.setImage(post.getImage());

		when(postMapper.convertToDTO(post)).thenReturn(responseDTO);

		// Act
		PostResponseDTO result = postService.createPost(postRequestDTO);

		// Assert
		assertNotNull(result);
		assertEquals(post.getId(), result.getId());

		// Verify
		verify(projectRepository, times(1)).findById(postRequestDTO.getProject());
		verify(studentRepository, times(1)).findById(postRequestDTO.getStudent());
		verify(postMapper, times(1)).convertToEntity(postRequestDTO);
		verify(postRepository, times(1)).save(post);
		verify(postMapper, times(1)).convertToDTO(post);
	}

	@Test
	public void testCreatePost_ProjectNotFound() {
		PostRequestDTO requestDTO = new PostRequestDTO();
		requestDTO.setStudent(1L);
		requestDTO.setProject(2L);
		requestDTO.setDemoUrl("demoUrl");
		requestDTO.setRepoUrl("repoUrl");
		requestDTO.setDescription("Description");
		String contentType = "image/png";
		String name = "Nombre de foto";
		String base64Image = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYVFRgWFRYYGBgaGBgYGhgYGhgYGBgYGBgZGRgYGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISHjQrJCE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ/ND80Mf/AABEIAOEA4QMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAEAAIDBQYBB//EADIQAAIBAwMDAwMDBAIDAQAAAAABAgMEEQUSITFBUQYiYTJxgRORsVKhwdFC8CMzghT/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABQT/xAAgEQEBAQEBAAMBAQADAAAAAAAAAQIRIQMSMUFREyIy/9oADAMBAAIRAxEAPwDITiB3FHDyi0nAHnDyA4SitwZZ2vJDGDi+FlFnpTbljt4YeNzq1jpSmnKPRx4XyWFDRFCMW3jhZLnQKEdn+Am8o9l0BrX1VziUZpkIRilBpljFsw9dTpvdCTQyOv1U/qF/5v8ATf8AH/jfYGykZqw9R5WJr8l3aX0Kn0tGm5S3NieTZzYEOKRzI6aGNMcqIRCBIomYJ+gMqtRRNWngrq9TPCB00iCU3KRIoBVtZtLLQo0+RbBchS4CqMBQiNr1u0TcZDf3PG1Ffb2izulyGKm+vcc6bwNI1cyksIinIeyKXUpIRNT56kuBkEdkzVoTGs6cSFrFlCFhHAC8jZHOBNJDUmzQpWllKbxF8mj0/wBNzg90pL9mT+maKzmUcJdzSXLXVdBda4rnPXbCjsjhElzDgVnLsPrSRHWvstMqK/hnKMxfQ2s11yuWVF1RTeMEbOGnVJGpwSULqUXmLaI6trJNxS8jYUnFrI01xrGr0f1M1JQqfubWjKMkpReUzxa7nh4+TRaL6mqUlGMuYL+Cudp6y9OOSlgCsdUhVinGSz4Ja8ysvYlc+oLqQywo5eWhTjuYdSp7Ym6NgqMUDVoE1GZHcGgB2hkoDZ1COVUaZBKmkR1J5IlNiQ0yXpk5DKS5yKsyWjHgpJ/A6lY0cxjROt11jd4mhYBRNwIdu+BCi8rjTz0NDo2jxxvnn4HaVpOVulwXcntjhC6+TOVPj+PoW7j7WocA9hdSj7Zk7YPW4PLr5O16M44uKV0opsiurpYUsrnj8lNG57EU6jnJLHEOF931/Zfyaa62pxaSnkHqxAbnUI011/ADD1NCUsSi18rlG5aWbn5R9eGOUuQKtS4XIa7qE45hJS+3YHkhb4aKO4tZuTl2FQ54DriXDAYT2fkaUtE29zKk8xm1jtk1Oler4SxGpw+mTF1YbYOT6lfQy+R86JXt9hVjPmLTQfUn2PGtL1epS5jJ8djY6N6uhLiosPyUmi2NvBqPUFu6+eEDR1CE17JJjMlMks4WTj5HpHYxKkpsYinwh7ZHUlwboBm8yDIrggt4c5CEU/jRxjTrG5JUYUjgjoouYEIQeQAbhtWAOvIfc3uOAJ3cWczWvs6WcyQ2cga5kWGxNENeisCZaqRTeSO/vlSjtTzL/LHXT2ZfOewNY6e5S3z58IrlD5L/ABUzoVKrzh8/cjuNHnFZ6myVNdlgbOCwUzbEfowdK4cHw2mjW6LWjWj19yX4M7rVpsm2k8Mk9O3WyaXlj2faehnVzeNFe2soLO3d8rx9jOTk5T6YWeh6BB5X4ArjT4SeXFZ8rgh3j0SszdUt0MFa8QRqLzTpbWoNPjo+pm7+2lFYaaY2aFDRqPITCYJRWFz1HKfI0pVtbalOD9snwaHSvVnKjU6dMmJrzw0yKVXwUzrhbnr3C2qxklKLymTHjWk+pKtB4i214fQ0dv69ba3QL53Erlv6nQHqSILHUoVoKUX+B/1SRTPKS+C6MMIeJdDjGoQ1jWdycEvR6SOHDuAcM6IXIgsra1gpclXc2DjyadLjgguKOU0cqx0ZpkP/ANTi8BLvU0R3+mvLaBYWsspdu4sG2SJXbqcsvp4CZRx/oc+CGc1nqUnYhztNchkpCbOZQ/Rs5FXr1PdDPgy1CW2Sfhmyuqe6LXwzGXEMSa+Sub5x5vknL16Rp1bfCLCW8lH6Zr7oY8F3kjqcq+PYjnAGvVFQbkk0l3DZxyUPqWtiMYLrJ5f2QJ7R5xmLjh588jY0+426XPPbgIjHKx4S/uVIr7mfIoPKO3du1y0MprCD+BXVAntoLPJxIlow8BnaVrfTFRqWE+PBurOnxlmG9LUXv5R6DThhI9nxTz1LZzI5EsiGTG0WFI4LIsiWs4JCEjQXcCEIwk+ECRr5lg7Tr54Fc08e5HKdAJVecoqbiajwFV7lRy30wZqtqMZzaT5DnPQ1rzgyrdPsQuowGNfcwmEhrmwkvE6kJI51F06A9NXZcmV1SlibNRJFLrlF8SX5K4qHyZ676butk9rfXsbWLR51YT2TUl2N5aVlOCkbeSfHrngsxuvXKU3J8vol4S6GnvLnZH5fCMJrss1PuLmf1bV8DOe/r9w2mvb/ACCWdPMi2m4xWPjp4Kc9J1C6e9NvokVE5JNpeQ6rdcNIA2jcLRNOXAVSWASiiWE+QwG+9LPKTa6dzYxPPdAjVaWyLS8m2tP1Nq34PXi+JanaMbI5D5MjbNqtHDh0TBzrEcEIH8Y4Q3IgMBnTcZBdZ7oP7EtSnujx2BISzlPwcyeOj1n9RoxcXHPVGB1G0qUJuXWPlG9vINSefJWX9CM4NS8cBx4n8mesfbapjqy2oaxF/cqXp0G2m8f7AK9rKEuHwen69ea71mtvSrbkSSZkbDWHB4kaG0vozXBLWOK53KMZDe0t8Gu/UcpBEVxwLnyqanYykY7eGaX09drGxsrdTtHnclwEaFbvO5lrZxGZ9H6hUcqiX/GK/uZbVHuqNmj1SpiOV3ZmYQbnLPyxMw1EWK2vL6YYJdXTc3gsJw/8Sa64Ku2p7pPyP+AJ/QePvj/eQapL3bV24Ly4pYXH9OP7FDRj7/yMUa44iorqzrW1/I+EH2WWSqio8y5fhf5NAa/0frGfZLj5NqpZPHbW5cZxfRJ9j1ixqZhF+Uj0Y10tgiQxyOyfA1jX9J13ImxDWzMR3IxsW7g0au7hDdwgAJt59iC8tf8AlH9hy4YUuhzudnHv+3GTv554ksfJUVl2Zs9R02M0ZavauMnGWeOjF+tlN2Vnr+ySW6JS103w10NZdWuVlMpqiUX7oqS/73KZ+Sz9R38Uvsqtt7BTWGvyNjbyoTUU/bkurWkpf+uW1/0v/ZFe2039Uc/wVupYjMWUZSlnD8htNMrtPTfDWGi1hHjJHT0Z/PT/ANPdw0FQt0ovCwhlODysB0oe3Hhf3FyNZLVoOS2rjnJUW0ec/Beapw2vj+SttodclZ/hNJKtP2xjnHd/YjsaC35/Iy4q5X/zgKsIN8/ZDyE6IuKXt/d/gzcViTwu5tJWrcH8lXDSlF56sP1L022pYj4IriUUsIJq0pdM4RW1aTXyHnAtMklnJ6d6fr7qUfsjzOnhtJ+T1DR6cVTio+B8SgsnI4cOJliuykRykKchmQ2FtOycchu4a5AsY7IiPIgCsdoVSjkHCaB4ZHq1UkqZX3lrGXVFtGOURVqZT6zhZrlYXU7Hl7UUV5ZZ4ksfJ6DdW2U+PyUd9bpxxjLJXPqn26wcqUqcsx7eDSabfRqRW7r8jLm1ygH9PY8o3LBWdWEE+OPsKjBz4islRUuQ/RNQ2y5F1TSTi6sKLb54wTXS25DVcqSyVGo1so2eFs4zmpS97bK6c8JpBd/ym/nJR3NfL/BXKWrw6jFykoryaewUIRzJpJdWzOWaxyU2uarNz2Z9qfK8l85iWtcb669U21NfWn8R5M7eetYNvbBvn7GHqyy20sDBuJ/atjLX3KKlt4bwGUbjcs8mbs6OYwj85NDt2xwJf08toqxpudSKwnyj06ygowSSwYb0tZylLf2RuqMGl1GyNqdsamNkzm4r/U3WROWDs5rAPu3MahEjmNbOSGuQonCItx0wrinNSQRQmUdGo49GmWdtUyc/N69mouIPgdU6EVvPKH1UsFp+JWcoOrhlHewWQu+cuxTXVZp4beSVvDSBrqnhMo7gtq91tXLK+pFTW6Il11WRTuGXgOtKah1Y79PaDKGZfYSnk8XUL9xWM8A11dNoFjEiqrEWPCaVuo3HGE+5UTfIVdS9xXVp8l8x59X0e7pRh8mcu6LbcvIVOrlh1GEWuSsqdnYzig/ARbWsm+hoadrRzzIKhXow+mOWa68aZhum2eyO6XX5E6u+e1ecA91fSnwuF4Ln0npLqT3y+lA/R5G09PWahBIvYsGhBRSS7D/1B5OF16kmyKTOuWSCtMqT+uSZ3IO5joyBL6Y6UzkpcELYnINBJvEQbxA6Kwa+M/gbT9ryuP3K+NKqukv7kT355mv3OXmvfcxsbO4yGTmsdTI2104/81+5e2N0prqn9i2dI6yhrzeWA3NCM18lpXhzyiruabjygabNZy9o7ZNS6ElnGGPb3DL233r5ALWm4vaxJFPsEu6bzwDwpsO1JODi8cN8hkrPEU/ItimfYqtpy7pYg2GTp9ga/wDoaHxE9MpfywU9zIstReGUtSeWXnjzaKC5CWiGnEJjAYqHYSQi/AVRoF1pejucl4NzpugdH0idaaWMLPLPUdM02FGCil06s7pekxpxXHIbOJaZ4W1FOWBJpLLGzgRuk31fQMK7OqscAdSpgInTwyGdBPuG9AyNTydcxSp47jHBmkDru4bUnhCcAW5Zhd/U+RAO5nTC0Dh4AKlHL5S+4ck/JHOOTkuhfVVcwS6t/gK0XUYwljnOSG8n2zgoZXO2Tw8Mpmk09XpVFUjkGuKXYzfpbVtzUX0NdcR4yWkTkUlShtZyVqpcrhlmkmcVNIP0a+fqnurFSjyiOrhxS8Iupoz1/Bxmsd2DWfFPh16CrLkCuY5RZXiwVleXAmer7zLGW1an1KKFBtmn1ChKWcIAjabVyXjw7nKBhQQTbU02kKpDPQItaTXLDE60mn6PFxTa+TTaVaJPCXQz2lXeXtyzY6dCWMprkfOet0a3hA82PqzfjP2B6lZFf4Tpk5CjIhlUOqXBsT1qjqS5Gbxk5kSmHv8A2ZNOZH+qcqS4BHUDqcD9T1KoJUmKU8g85E+jxJuEQ7xG6y4lc57jVcS7vgrFXXYmVVPucma66dy7ex3d1+5SVLTa2/5LGtOOOAKpVfbkeeJ0zSrmUKi8Z5PVKVRTgmueDy5UVJcdTQemdWdNuE3xxgtmkrQRs9snJN/vwFqfHITBxmsohqwKNagnMp9VlymG3DfYrHVxNOXQw5knpisJz5SJHoqivfyy5truDXtaIby6i+4cydbfyW+MxfWsUuCguLTL4kjSXTg08yWPuUdW4pRb2vcx+vPehIWOOmGQVpRTxnDJZ6hKXHT7dV8/JBVnGXE+r6TXR/f5N0EtnUcZJ9UejaPfxnBY8Hlk3KD+C69PatJTSb4fA2NcLXoFSo2wWoKNXjgjqTK2kiNvkfKeERKR2tPgOWoacxqmRTmM3A/phc5e0CcyWMsoElIfX4WOykRyY2UxjmQonbjpHkRmSXNNxYFXqNGguKGUUl7aM5PHUBRuV3GXE1hbe4LOO19CGpWaftLZT0sJOUVuzyguw1CL5muSqd6+FN8cZRK7qEcSXnoOT8ekaJq6cVGXBdVZJrqebWuqRccpYx+5LP1ZKPCbGzoL621eOSsuKaM/T9XPPKINT9QOa9vA/Qo+5qxhzux8ZM3e6rKTajJ4KytdSm+W2RRjl4yH7J8vU9apPHLb/JBTrtPx2GVoT6Mjopp8rKN0Es6zzt/Z+PgdCtx7llZxKPh/1ImhTi0njnJY0LXd0ijDycAwT4X1RfR/4ZLRtmnujlfHgsqdtFcNr7Crw2/Sx4Rd6RcyccNlhKoUmlVl0b5LNTLT1OwRGRHWmRSqEM6g8vANnIicxk58kTmLR6Poz4A6ssHadTBDcy5Hv/kP6UpjHMY5DJSIid+oIhz8iCLWMrr3uIRyY6bPXvUrKn1CEVz+J6DVepDV6o6IclW+nfU/sC3X1v7iEaN/Ch/kmrfSdEMWgYdRsvrQhBATAUujEIZN226fkubToIQZ+iiX1f8AfI+v9X4EIaFqS0+ouYCEWySuzIJCENSoJnBCBWcGVxCHv4H9RIZIQiY1EIQgM//Z";
		byte[] content = Base64.getDecoder().decode(base64Image);
		MultipartFile multipartFile = new MockMultipartFile(name, name, contentType, content);
		requestDTO.setImage(multipartFile);

		Project project = new Project();
		project.setId(1L);

		when(projectRepository.findById(requestDTO.getProject())).thenReturn(Optional.empty());

		assertThrows(ResourceNotFoundException.class, () -> postService.createPost(requestDTO));

		verify(projectRepository, times(1)).findById(requestDTO.getProject());
	}

	@Test
	public void testCreatePost_StudentNotFound() {
		PostRequestDTO requestDTO = new PostRequestDTO();
		requestDTO.setStudent(2L);
		requestDTO.setProject(1L);
		requestDTO.setDemoUrl("demoUrl");
		requestDTO.setRepoUrl("repoUrl");
		requestDTO.setDescription("Description");
		String contentType = "image/png";
		String name = "Nombre de foto";
		String base64Image = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoHCBYVFRgWFRYYGBgaGBgYGhgYGhgYGBgYGBgZGRgYGBgcIS4lHB4rIRgYJjgmKy8xNTU1GiQ7QDs0Py40NTEBDAwMEA8QHhISHjQrJCE0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ0NDQ/ND80Mf/AABEIAOEA4QMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAAEAAIDBQYBB//EADIQAAIBAwMDAwMDBAIDAQAAAAABAgMEEQUSITFBUQYiYTJxgRORsVKhwdFC8CMzghT/xAAZAQADAQEBAAAAAAAAAAAAAAABAgMABQT/xAAgEQEBAQEBAAMBAQADAAAAAAAAAQIRIQMSMUFREyIy/9oADAMBAAIRAxEAPwDITiB3FHDyi0nAHnDyA4SitwZZ2vJDGDi+FlFnpTbljt4YeNzq1jpSmnKPRx4XyWFDRFCMW3jhZLnQKEdn+Am8o9l0BrX1VziUZpkIRilBpljFsw9dTpvdCTQyOv1U/qF/5v8ATf8AH/jfYGykZqw9R5WJr8l3aX0Kn0tGm5S3NieTZzYEOKRzI6aGNMcqIRCBIomYJ+gMqtRRNWngrq9TPCB00iCU3KRIoBVtZtLLQo0+RbBchS4CqMBQiNr1u0TcZDf3PG1Ffb2izulyGKm+vcc6bwNI1cyksIinIeyKXUpIRNT56kuBkEdkzVoTGs6cSFrFlCFhHAC8jZHOBNJDUmzQpWllKbxF8mj0/wBNzg90pL9mT+maKzmUcJdzSXLXVdBda4rnPXbCjsjhElzDgVnLsPrSRHWvstMqK/hnKMxfQ2s11yuWVF1RTeMEbOGnVJGpwSULqUXmLaI6trJNxS8jYUnFrI01xrGr0f1M1JQqfubWjKMkpReUzxa7nh4+TRaL6mqUlGMuYL+Cudp6y9OOSlgCsdUhVinGSz4Ja8ysvYlc+oLqQywo5eWhTjuYdSp7Ym6NgqMUDVoE1GZHcGgB2hkoDZ1COVUaZBKmkR1J5IlNiQ0yXpk5DKS5yKsyWjHgpJ/A6lY0cxjROt11jd4mhYBRNwIdu+BCi8rjTz0NDo2jxxvnn4HaVpOVulwXcntjhC6+TOVPj+PoW7j7WocA9hdSj7Zk7YPW4PLr5O16M44uKV0opsiurpYUsrnj8lNG57EU6jnJLHEOF931/Zfyaa62pxaSnkHqxAbnUI011/ADD1NCUsSi18rlG5aWbn5R9eGOUuQKtS4XIa7qE45hJS+3YHkhb4aKO4tZuTl2FQ54DriXDAYT2fkaUtE29zKk8xm1jtk1Oler4SxGpw+mTF1YbYOT6lfQy+R86JXt9hVjPmLTQfUn2PGtL1epS5jJ8djY6N6uhLiosPyUmi2NvBqPUFu6+eEDR1CE17JJjMlMks4WTj5HpHYxKkpsYinwh7ZHUlwboBm8yDIrggt4c5CEU/jRxjTrG5JUYUjgjoouYEIQeQAbhtWAOvIfc3uOAJ3cWczWvs6WcyQ2cga5kWGxNENeisCZaqRTeSO/vlSjtTzL/LHXT2ZfOewNY6e5S3z58IrlD5L/ABUzoVKrzh8/cjuNHnFZ6myVNdlgbOCwUzbEfowdK4cHw2mjW6LWjWj19yX4M7rVpsm2k8Mk9O3WyaXlj2faehnVzeNFe2soLO3d8rx9jOTk5T6YWeh6BB5X4ArjT4SeXFZ8rgh3j0SszdUt0MFa8QRqLzTpbWoNPjo+pm7+2lFYaaY2aFDRqPITCYJRWFz1HKfI0pVtbalOD9snwaHSvVnKjU6dMmJrzw0yKVXwUzrhbnr3C2qxklKLymTHjWk+pKtB4i214fQ0dv69ba3QL53Erlv6nQHqSILHUoVoKUX+B/1SRTPKS+C6MMIeJdDjGoQ1jWdycEvR6SOHDuAcM6IXIgsra1gpclXc2DjyadLjgguKOU0cqx0ZpkP/ANTi8BLvU0R3+mvLaBYWsspdu4sG2SJXbqcsvp4CZRx/oc+CGc1nqUnYhztNchkpCbOZQ/Rs5FXr1PdDPgy1CW2Sfhmyuqe6LXwzGXEMSa+Sub5x5vknL16Rp1bfCLCW8lH6Zr7oY8F3kjqcq+PYjnAGvVFQbkk0l3DZxyUPqWtiMYLrJ5f2QJ7R5xmLjh588jY0+426XPPbgIjHKx4S/uVIr7mfIoPKO3du1y0MprCD+BXVAntoLPJxIlow8BnaVrfTFRqWE+PBurOnxlmG9LUXv5R6DThhI9nxTz1LZzI5EsiGTG0WFI4LIsiWs4JCEjQXcCEIwk+ECRr5lg7Tr54Fc08e5HKdAJVecoqbiajwFV7lRy30wZqtqMZzaT5DnPQ1rzgyrdPsQuowGNfcwmEhrmwkvE6kJI51F06A9NXZcmV1SlibNRJFLrlF8SX5K4qHyZ676butk9rfXsbWLR51YT2TUl2N5aVlOCkbeSfHrngsxuvXKU3J8vol4S6GnvLnZH5fCMJrss1PuLmf1bV8DOe/r9w2mvb/ACCWdPMi2m4xWPjp4Kc9J1C6e9NvokVE5JNpeQ6rdcNIA2jcLRNOXAVSWASiiWE+QwG+9LPKTa6dzYxPPdAjVaWyLS8m2tP1Nq34PXi+JanaMbI5D5MjbNqtHDh0TBzrEcEIH8Y4Q3IgMBnTcZBdZ7oP7EtSnujx2BISzlPwcyeOj1n9RoxcXHPVGB1G0qUJuXWPlG9vINSefJWX9CM4NS8cBx4n8mesfbapjqy2oaxF/cqXp0G2m8f7AK9rKEuHwen69ea71mtvSrbkSSZkbDWHB4kaG0vozXBLWOK53KMZDe0t8Gu/UcpBEVxwLnyqanYykY7eGaX09drGxsrdTtHnclwEaFbvO5lrZxGZ9H6hUcqiX/GK/uZbVHuqNmj1SpiOV3ZmYQbnLPyxMw1EWK2vL6YYJdXTc3gsJw/8Sa64Ku2p7pPyP+AJ/QePvj/eQapL3bV24Ly4pYXH9OP7FDRj7/yMUa44iorqzrW1/I+EH2WWSqio8y5fhf5NAa/0frGfZLj5NqpZPHbW5cZxfRJ9j1ixqZhF+Uj0Y10tgiQxyOyfA1jX9J13ImxDWzMR3IxsW7g0au7hDdwgAJt59iC8tf8AlH9hy4YUuhzudnHv+3GTv554ksfJUVl2Zs9R02M0ZavauMnGWeOjF+tlN2Vnr+ySW6JS103w10NZdWuVlMpqiUX7oqS/73KZ+Sz9R38Uvsqtt7BTWGvyNjbyoTUU/bkurWkpf+uW1/0v/ZFe2039Uc/wVupYjMWUZSlnD8htNMrtPTfDWGi1hHjJHT0Z/PT/ANPdw0FQt0ovCwhlODysB0oe3Hhf3FyNZLVoOS2rjnJUW0ec/Beapw2vj+SttodclZ/hNJKtP2xjnHd/YjsaC35/Iy4q5X/zgKsIN8/ZDyE6IuKXt/d/gzcViTwu5tJWrcH8lXDSlF56sP1L022pYj4IriUUsIJq0pdM4RW1aTXyHnAtMklnJ6d6fr7qUfsjzOnhtJ+T1DR6cVTio+B8SgsnI4cOJliuykRykKchmQ2FtOycchu4a5AsY7IiPIgCsdoVSjkHCaB4ZHq1UkqZX3lrGXVFtGOURVqZT6zhZrlYXU7Hl7UUV5ZZ4ksfJ6DdW2U+PyUd9bpxxjLJXPqn26wcqUqcsx7eDSabfRqRW7r8jLm1ygH9PY8o3LBWdWEE+OPsKjBz4islRUuQ/RNQ2y5F1TSTi6sKLb54wTXS25DVcqSyVGo1so2eFs4zmpS97bK6c8JpBd/ym/nJR3NfL/BXKWrw6jFykoryaewUIRzJpJdWzOWaxyU2uarNz2Z9qfK8l85iWtcb669U21NfWn8R5M7eetYNvbBvn7GHqyy20sDBuJ/atjLX3KKlt4bwGUbjcs8mbs6OYwj85NDt2xwJf08toqxpudSKwnyj06ygowSSwYb0tZylLf2RuqMGl1GyNqdsamNkzm4r/U3WROWDs5rAPu3MahEjmNbOSGuQonCItx0wrinNSQRQmUdGo49GmWdtUyc/N69mouIPgdU6EVvPKH1UsFp+JWcoOrhlHewWQu+cuxTXVZp4beSVvDSBrqnhMo7gtq91tXLK+pFTW6Il11WRTuGXgOtKah1Y79PaDKGZfYSnk8XUL9xWM8A11dNoFjEiqrEWPCaVuo3HGE+5UTfIVdS9xXVp8l8x59X0e7pRh8mcu6LbcvIVOrlh1GEWuSsqdnYzig/ARbWsm+hoadrRzzIKhXow+mOWa68aZhum2eyO6XX5E6u+e1ecA91fSnwuF4Ln0npLqT3y+lA/R5G09PWahBIvYsGhBRSS7D/1B5OF16kmyKTOuWSCtMqT+uSZ3IO5joyBL6Y6UzkpcELYnINBJvEQbxA6Kwa+M/gbT9ryuP3K+NKqukv7kT355mv3OXmvfcxsbO4yGTmsdTI2104/81+5e2N0prqn9i2dI6yhrzeWA3NCM18lpXhzyiruabjygabNZy9o7ZNS6ElnGGPb3DL233r5ALWm4vaxJFPsEu6bzwDwpsO1JODi8cN8hkrPEU/ItimfYqtpy7pYg2GTp9ga/wDoaHxE9MpfywU9zIstReGUtSeWXnjzaKC5CWiGnEJjAYqHYSQi/AVRoF1pejucl4NzpugdH0idaaWMLPLPUdM02FGCil06s7pekxpxXHIbOJaZ4W1FOWBJpLLGzgRuk31fQMK7OqscAdSpgInTwyGdBPuG9AyNTydcxSp47jHBmkDru4bUnhCcAW5Zhd/U+RAO5nTC0Dh4AKlHL5S+4ck/JHOOTkuhfVVcwS6t/gK0XUYwljnOSG8n2zgoZXO2Tw8Mpmk09XpVFUjkGuKXYzfpbVtzUX0NdcR4yWkTkUlShtZyVqpcrhlmkmcVNIP0a+fqnurFSjyiOrhxS8Iupoz1/Bxmsd2DWfFPh16CrLkCuY5RZXiwVleXAmer7zLGW1an1KKFBtmn1ChKWcIAjabVyXjw7nKBhQQTbU02kKpDPQItaTXLDE60mn6PFxTa+TTaVaJPCXQz2lXeXtyzY6dCWMprkfOet0a3hA82PqzfjP2B6lZFf4Tpk5CjIhlUOqXBsT1qjqS5Gbxk5kSmHv8A2ZNOZH+qcqS4BHUDqcD9T1KoJUmKU8g85E+jxJuEQ7xG6y4lc57jVcS7vgrFXXYmVVPucma66dy7ex3d1+5SVLTa2/5LGtOOOAKpVfbkeeJ0zSrmUKi8Z5PVKVRTgmueDy5UVJcdTQemdWdNuE3xxgtmkrQRs9snJN/vwFqfHITBxmsohqwKNagnMp9VlymG3DfYrHVxNOXQw5knpisJz5SJHoqivfyy5truDXtaIby6i+4cydbfyW+MxfWsUuCguLTL4kjSXTg08yWPuUdW4pRb2vcx+vPehIWOOmGQVpRTxnDJZ6hKXHT7dV8/JBVnGXE+r6TXR/f5N0EtnUcZJ9UejaPfxnBY8Hlk3KD+C69PatJTSb4fA2NcLXoFSo2wWoKNXjgjqTK2kiNvkfKeERKR2tPgOWoacxqmRTmM3A/phc5e0CcyWMsoElIfX4WOykRyY2UxjmQonbjpHkRmSXNNxYFXqNGguKGUUl7aM5PHUBRuV3GXE1hbe4LOO19CGpWaftLZT0sJOUVuzyguw1CL5muSqd6+FN8cZRK7qEcSXnoOT8ekaJq6cVGXBdVZJrqebWuqRccpYx+5LP1ZKPCbGzoL621eOSsuKaM/T9XPPKINT9QOa9vA/Qo+5qxhzux8ZM3e6rKTajJ4KytdSm+W2RRjl4yH7J8vU9apPHLb/JBTrtPx2GVoT6Mjopp8rKN0Es6zzt/Z+PgdCtx7llZxKPh/1ImhTi0njnJY0LXd0ijDycAwT4X1RfR/4ZLRtmnujlfHgsqdtFcNr7Crw2/Sx4Rd6RcyccNlhKoUmlVl0b5LNTLT1OwRGRHWmRSqEM6g8vANnIicxk58kTmLR6Poz4A6ssHadTBDcy5Hv/kP6UpjHMY5DJSIid+oIhz8iCLWMrr3uIRyY6bPXvUrKn1CEVz+J6DVepDV6o6IclW+nfU/sC3X1v7iEaN/Ch/kmrfSdEMWgYdRsvrQhBATAUujEIZN226fkubToIQZ+iiX1f8AfI+v9X4EIaFqS0+ouYCEWySuzIJCENSoJnBCBWcGVxCHv4H9RIZIQiY1EIQgM//Z";
		byte[] content = Base64.getDecoder().decode(base64Image);
		MultipartFile multipartFile = new MockMultipartFile(name, name, contentType, content);
		requestDTO.setImage(multipartFile);

		Project project = new Project();
		project.setId(1L);

		// Long studentId = 999L;
		Student student = new Student();
		student.setId(1L);

		when(projectRepository.findById(requestDTO.getProject())).thenReturn(Optional.of(project));
		when(studentRepository.findById(requestDTO.getStudent())).thenReturn(Optional.empty());

		assertThrows(ResourceNotFoundException.class, () -> postService.createPost(requestDTO));

		verify(projectRepository, times(1)).findById(requestDTO.getProject());
		verify(studentRepository, times(1)).findById(requestDTO.getStudent());
	}
	
	@Test
	public void getPostByStudentAndProject_Succesful(){
		// Arrange
		Long studentId = 1L;
		Long projectId = 1L;

		Project project = new Project();
		project.setId(projectId);
		project.setTitle("Titulo del proyecto");
		project.setDescription("Descripcion del proyecto");
		String base64Image = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		project.setImage(Base64.getDecoder().decode(base64Image));
		project.setLevel(1);

		Student student = new Student();
		student.setId(studentId);
		student.setUsername("pepito");
		student.setStatus("active");
		student.setDescription("Descripcion del estudiante");
		student.setEmail("pepito@gmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image2 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image2));

		Post post = new Post();
		post.setId(1L);
		post.setDemoUrl("demo.com");
		post.setRepoUrl("repo.com");
		post.setDescription("Descripcion del post");
		post.setDate(LocalDate.now());
		String base64Image3 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		post.setImage(Base64.getDecoder().decode(base64Image3));

		when(projectRepository.findById(projectId)).thenReturn(Optional.of(project));	
		when(studentRepository.findById(studentId)).thenReturn(Optional.of(student));
		when(postRepository.findByStudentIdAndProjectId(studentId, projectId)).thenReturn(Optional.of(post));

		StudentResponseDTO studentResponse = new StudentResponseDTO();
		studentResponse.setId(studentId);
		studentResponse.setUsername(student.getUsername());
		studentResponse.setStatus(student.getStatus());
		studentResponse.setDescription(student.getDescription());
		studentResponse.setProfile_picture(student.getProfile_picture());

		when(studentMapper.convertStudentToResponse(student)).thenReturn(studentResponse);

		PostByStudentResponseDTO postResponse = new PostByStudentResponseDTO();
		postResponse.setId(post.getId());
		postResponse.setStudent(studentResponse);
		postResponse.setTitle(project.getTitle());
		postResponse.setDemoUrl(post.getDemoUrl());
		postResponse.setRepoUrl(post.getRepoUrl());
		postResponse.setDescription(post.getDescription());
		postResponse.setDate(post.getDate());
		postResponse.setImage(post.getImage());

		when(postMapper.convertToResponse(post)).thenReturn(postResponse);

		// Act
		PostByStudentResponseDTO result = postService.getPostByStudentAndProject(studentId, projectId);

		// Assert
		assertNotNull(result);
		assertEquals(post.getId(), result.getId());
		assertEquals(post.getDemoUrl(), result.getDemoUrl());
		assertEquals(post.getRepoUrl(), result.getRepoUrl());
		assertEquals(post.getDescription(), result.getDescription());
		assertEquals(post.getDate(), result.getDate());
		assertEquals(post.getImage(), result.getImage());
		
		// Verify
		verify(projectRepository, times(1)).findById(projectId);
		verify(studentRepository, times(1)).findById(studentId);
		verify(postRepository, times(1)).findByStudentIdAndProjectId(studentId, projectId);
		verify(studentMapper, times(1)).convertStudentToResponse(student);
		verify(postMapper, times(1)).convertToResponse(post);
	}

	@Test
	public void getPostByStudentAndProject_ProjectNotFound(){
		// Arrange
		Long studentId = 1L;
		Long projectId = 1L;

		when(projectRepository.findById(projectId)).thenReturn(Optional.empty());

		// Act & Assert
        assertThrows(ResourceNotFoundException.class, () -> postService.getPostByStudentAndProject(studentId, projectId));
	}

	@Test
	public void getPostByStudentAndProject_StudentNotFound() {
		// Arrange
		Long studentId = 1L;
		Long projectId = 1L;

		Project project = new Project();
		project.setId(projectId);

		when(projectRepository.findById(projectId)).thenReturn(Optional.of(project));
		when(studentRepository.findById(studentId)).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getPostByStudentAndProject(studentId, projectId));

		// Verify
		verify(projectRepository, times(1)).findById(projectId);
	}

	@Test
	public void getPostByStudentAndProject_PostNotFound() {
		// Arrange
		Long studentId = 1L;
		Long projectId = 1L;

		Project project = new Project();
		project.setId(projectId);
		project.setTitle("Titulo del proyecto");
		project.setDescription("Descripcion del proyecto");
		String base64Image = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		project.setImage(Base64.getDecoder().decode(base64Image));
		project.setLevel(1);

		Student student = new Student();
		student.setId(studentId);
		student.setUsername("pepito");
		student.setStatus("active");
		student.setDescription("Descripcion del estudiante");
		student.setEmail("pepito@gmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image2 = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image2));

		when(projectRepository.findById(projectId)).thenReturn(Optional.of(project));
		when(studentRepository.findById(studentId)).thenReturn(Optional.of(student));
		when(postRepository.findByStudentIdAndProjectId(studentId, projectId)).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getPostByStudentAndProject(studentId, projectId));

		// Verify
		verify(projectRepository, times(1)).findById(projectId);
		verify(studentRepository, times(1)).findById(studentId);
	}

	@Test 
	public void testGetAllPostsByProjectId_ExistingId(){
		// Arrange
		Long id = 1L;

		Student student1 = new Student();
		Student student2 = new Student();
		student1.setId(1L);
		student1.setUsername("student1");
		student1.setEmail("student1@gmail.com");
		student1.setPwd("contrasenafacilita");

		student2.setId(2L);
		student2.setUsername("student2");
		student2.setEmail("student2@gmail.com");
		student2.setPwd("contrasenafacilita2");

		// Agregar datos simulados a posts
		List<Object[]> posts = new ArrayList<>(List.of(
			new Object[]{1L, student1, 10L, 5L, LocalDate.parse("2024-01-01"), null}, 
			new Object[]{2L, student2, 15L, 10L, LocalDate.parse("2024-03-10"), null}
		));

		// Crear posts esperados simulados
		List<PostByProjectResponseDTO> expectedPosts = posts.stream()
				.map(postData -> {
					PostByProjectResponseDTO postByProjectResponse = new PostByProjectResponseDTO();
					postByProjectResponse.setId((Long) postData[0]);
					postByProjectResponse.setStudent((Student) postData[1]);
					postByProjectResponse.setRockets((Long) postData[2]);
					postByProjectResponse.setComments((Long) postData[3]);
					postByProjectResponse.setDate((LocalDate) postData[4]);
					postByProjectResponse.setImage((byte[]) postData[5]);
					return postByProjectResponse;
				})
				.collect(Collectors.toList());

		// Configurar el comportamiento simulado del repositorio
		when(postRepository.findAllByProjectId(id)).thenReturn(Optional.of(posts));

		// Act
		List<PostByProjectResponseDTO> result = postService.getAllPostsByProjectId(id);

		// Assert
		assertEquals(expectedPosts.size(), result.size());

		// Verify that repository and mapper methods were called
		verify(postRepository, times(1)).findAllByProjectId(id);
	}

	@Test
	public void testGetAllPostsByProjectId_NonExistingId() {
		// Arrange
		Long id = 999L;

		// Configurar el comportamiento simulado del repositorio
		when(postRepository.findAllByProjectId(id)).thenReturn(Optional.empty());

		// Act & Assert
        assertThrows(ResourceNotFoundException.class, () -> postService.getAllPostsByProjectId(id));

		// Verify 
		verify(postRepository, times(1)).findAllByProjectId(id);
	}

	@Test
	public void testGeAllPostsByStudent_Successful() {
		// Arrange
		Long studentId = 1L;

		Student student = new Student();
		student.setId(studentId);
		student.setUsername("student1");
		student.setEmail("student1@gmail.com");
		student.setPwd("contrasenafacilita");
		String base64Image = "iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAM1BMVEXk5ueutLeqsbTn6eqpr7PJzc/j5ebf4eLZ3N2wtrnBxsjN0NLGysy6v8HT1tissra8wMNxTKO9AAAFDklEQVR4nO2d3XqDIAxAlfivoO//tEOZWzvbVTEpic252W3PF0gAIcsyRVEURVEURVEURVEURVEURVEURVEURVEURVEURflgAFL/AirAqzXO9R7XNBVcy9TbuMHmxjN6lr92cNVVLKEurVfK/zCORVvW8iUBnC02dj+Wpu0z0Y6QlaN5phcwZqjkOkK5HZyPAjkIjSO4fIdfcOwFKkJlX4zPu7Ha1tIcwR3wWxyFhRG6g4Je0YpSPDJCV8a2Sv2zd1O1x/2WMDZCwljH+clRrHfWCLGK8REMiql//2si5+DKWKcWeAGcFMzzNrXC/0TUwQ2s6+LhlcwjTMlYsUIQzPOCb7YBiyHopyLXIEKPEkI/TgeuiidK/R9FniUDOjRDpvm0RhqjMyyXNjDhCfIMYl1gGjIMIuYsnGEYRMRZOMMunaLVwpWRW008v6fYKDIzxCwVAeNSO90BJW6emelYBRF/kHpYGVaoxTDAaxOFsfP9y8hpJ4xd7gOcij7JNGQ1EYFgkPJa1jQEiYZXRaRINKxSDUW9n+FT82lSKadkiru9/4XPqSLWOekGPoY05TAvLm9orm+YWuwHoBHkZKijNBJGmeb61eL6Ff/6q7bLr7yvv3vKGhpDRjvgjGaPz+gUg6YgcvpyAR2FIZ9U6nEEyZRTovmEU32KichpGn7C17XrfyH9gK/c0CMP05HZIM2uf9sEveizKveBy9/6Qt7o89ne33D525cfcIMW6ab+TMEukQbQbu+xu7X3A9bChmWaCeAkG17bpntwXgWxHaMzGPmUaR5dQZiKqRVeUZ3047fi3nAu28h4CHxCsZAgmEH8Y27jJAhm8c+5RQzRQNVGhVFSfxOYIjp/pP7RxzjevYXVGf4eLt+BJ1vCuLuLkrgABgCGXZ2wik5uty+oBvNirI6mkzhAf4Gsb58Hcm67Jzd+KwD10BYPLL3e0MjvKrgAULnOfveF/O4N2Xb9BZom3gJes3F9X5Zze8/6Yt09b4CrqsEjUv8oFBaR2rl+6CZr2xVrp24o/WitBKuGrrpl1+bFkmK2qXTON4VpbdfLa7o7y/WdLxG7lm2Lqh2clOwTegbvc/vj2U78CwhA87Bn8G5Nk3eOb0Nsr9flz3sG78UUtue4kpv1xvjg3TMay62BMlTlP+vrOMnJsRmt/ze0jsfkPPYdAH57hK+34PeOyc8XIXu5xT2HsUkdZz+adwg8HGFfQ3K5jtDvbUiO4Di9/ywHGrL88pDizZ++oTp+an+SMX/ndymUCwmHMdO7yuOx83pUx/eEMU0AvxWndwgidAqOZ8ypCwdEfvvEo6D9HwpA8wzvmOJEqAg9ySu8g4x0Hb9hSB/BANEKJ+LbPBU0lzbAJs4xt1AoshKkUGQmiH8/jJ0gdhTTLmSegHlPE0oOdXALnqDjKYh3px//fSgSWG8UqfrrIICzYYSJXRr9BSPbpNzw7gBjKjKOYI7ReIGqQRIap5+5MdjyvuDkExvGeXSlONWZAP3/AZBwJohU7QJRGU+cTVH18ELmRPNBmibW6MT/k1b0XhdkRBvyT6SB6EYv/GvhSmRNpGngRULsAlxMCGNXp7w3FfdEbTEEDdLI9TdIKRUzUesa3I461ER8cpNT7gMRhpKmYVS9ELOgCUQsa4SsulciKiLbY+AnHD8cpuhISsnxpamI84sbDq9qYJgf8wiiOBrC7Ml7M7ZECCqKoiiKoiiKoiiKoijv5AvJxlZRyNWWLwAAAABJRU5ErkJggg==";
		student.setProfile_picture(Base64.getDecoder().decode(base64Image));

		List<Object[]> posts = new ArrayList<>(List.of(
			new Object[] {1L, student, "Titulo 1", "Demo url 1", "Repo URL 1", "Descripcion 1", LocalDate.parse("2024-01-01"), null},
			new Object[] {2L, student, "Titulo 2", "Demo url 2", "Repo URL 2", "Descripcion 2", LocalDate.parse("2024-01-10"), null}
		));

		// Mocking repository
		when(studentRepository.findById(studentId)).thenReturn(Optional.of(student));
		when(postRepository.findAllByStudent(student)).thenReturn(Optional.of(posts));

		StudentResponseDTO studentResponseDTO = new StudentResponseDTO();
		studentResponseDTO.setId(student.getId());
		studentResponseDTO.setUsername(student.getUsername());
		studentResponseDTO.setStatus(student.getStatus());
		studentResponseDTO.setDescription(student.getDescription());
		studentResponseDTO.setProfile_picture(student.getProfile_picture());

		// Crear posts esperados simulados
		List<PostByStudentResponseDTO> expectedPosts = posts.stream()
				.map(postData -> {
					PostByStudentResponseDTO postByStudentResponse = new PostByStudentResponseDTO();
					postByStudentResponse.setId((Long) postData[0]);
					postByStudentResponse.setStudent(studentResponseDTO);
					postByStudentResponse.setTitle((String) postData[2]);
					postByStudentResponse.setDemoUrl((String) postData[3]);
					postByStudentResponse.setRepoUrl((String) postData[4]);
					postByStudentResponse.setDescription((String) postData[5]);
					postByStudentResponse.setDate(((LocalDate) postData[6]));
					postByStudentResponse.setImage((byte[]) postData[7]);
					return postByStudentResponse;
				})
				.collect(Collectors.toList());

		// Act
		List<PostByStudentResponseDTO> result = postService.getAllPostsByStudent(studentId);

		// Assert
		assertNotNull(result);
		assertEquals(expectedPosts.size(), result.size());

		// Verify that repository and mapper methods were called
		verify(studentRepository, times(1)).findById(studentId);
		verify(postRepository, times(1)).findAllByStudent(student);
	}

	@Test
	public void testGetAllPostsByStudent_StudentNotFound() {
		// Arrange
		Long studentId = 999L;

		// Mocking repository
		when(studentRepository.findById(studentId)).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getAllPostsByStudent(studentId));
	}

	@Test
	public void testGetAllPostsByStudent_PostsNotFound() {
		// Arrange
		Long studentId = 1L;

		Student student = new Student();
		student.setId(studentId);
		student.setUsername("student");
		student.setStatus("status");
		student.setDescription("decripcion");
		student.setEmail("student@gmail.com");
		student.setPwd("contrasenafacilita");
		student.setProfile_picture(null);

		// Simular que el estudiante existe pero los posts no
		when(studentRepository.findById(studentId)).thenReturn(Optional.of(student));
		when(postRepository.findAllByStudent(student)).thenReturn(Optional.empty());

		// Act & Assert
		assertThrows(ResourceNotFoundException.class, () -> postService.getAllPostsByStudent(studentId));
	}
}
